name: fail_test

on: 
  pull_request: 
    branches: main
  workflow_dispatch:

jobs:
  test_echo_fail:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run echo.
        run: |
         fail "hello ci/cd"
